/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/envirounment.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Terrain.geometry} material={materials.roof} />
      <mesh geometry={nodes.Terrain_envelope.geometry} material={nodes.Terrain_envelope.material} />
      <mesh geometry={nodes.maposm_buildings.geometry} material={materials.wall} rotation={[0, -0.16, 0]} />
      <mesh geometry={nodes.maposm_buildings001.geometry} material={materials.roof} rotation={[0, -0.16, 0]} />
    </group>
  )
}

useGLTF.preload('/envirounment.glb')
